CREATE TABLE `exames` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `numero` bigint DEFAULT NULL,
  `exame_id` bigint NOT NULL,
  `motivo_id` bigint DEFAULT NULL,
  `cliente_id` bigint NOT NULL,
  `empresa_id` bigint NOT NULL,
  `status` int NOT NULL DEFAULT '1',
  `arquivo_exame` varchar(200) NOT NULL,
  `arquivo_laudo` varchar(200) DEFAULT NULL,
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `observacoes` text,
  `observacoes_medico` text,
  `modelo_content` text,
  `arquivos_selecionados` varchar(255) DEFAULT NULL,
  `opcoes_impossibilitado` varchar(255) DEFAULT NULL,
  `paciente` varchar(100) DEFAULT NULL,
  `rg` varchar(20) DEFAULT NULL,
  `cpf` varchar(20) DEFAULT NULL,
  `nascimento` datetime DEFAULT NULL,
  `sexo` varchar(1) DEFAULT NULL,
  `funcao` varchar(50) DEFAULT NULL,
  `contratante` varchar(100) DEFAULT NULL,
  `ativo` int NOT NULL DEFAULT '1',
  `emergencia` int NOT NULL DEFAULT '0',
  `laudo_impossibilitado` int NOT NULL DEFAULT '0',
  `laudo_date` timestamp DEFAULT NULL,
  `exame_date` timestamp DEFAULT NULL,
  `medico_solicitante` varchar(100) DEFAULT NULL,
  `crm_solicitante` varchar(8) DEFAULT NULL,
  `sub_tipo_exame` varchar(100) DEFAULT NULL,
  `peso` decimal(10,2) DEFAULT NULL,
  `altura` decimal(10,2) DEFAULT NULL,
  `imc` decimal(10,2) DEFAULT NULL,
  `fumante` char(1) DEFAULT NULL,
  `fumante_tempo` varchar(100) DEFAULT NULL,
  `extra_data` text,
  `preco_exame` decimal(10,2) DEFAULT NULL,
  `preco_exame_medico` decimal(10,2) DEFAULT NULL,
  `baixado` int DEFAULT NULL,
  `acuidade_perto_od` varchar(45) DEFAULT NULL,
  `acuidade_perto_oe` varchar(45) DEFAULT NULL,
  `acuidade_longe_od` varchar(45) DEFAULT NULL,
  `acuidade_longe_oe` varchar(45) DEFAULT NULL,
  `lente_corretiva` varchar(45) DEFAULT NULL,
  `senso_cromatico` varchar(45) DEFAULT NULL,
  `visao_noturna` varchar(45) DEFAULT NULL,
  `visao_ofuscada` varchar(45) DEFAULT NULL,
  `profundidade` varchar(45) DEFAULT NULL,
  `crc` varchar(20) DEFAULT NULL,
  `rnd` varchar(10) DEFAULT NULL,
  `protocolo` varchar(25) DEFAULT NULL,
  `arquivo_laudo_assinado` varchar(100) DEFAULT NULL,
  `arquivo_imagem` varchar(200) DEFAULT NULL,
  `arquivo_id` varchar(200) DEFAULT NULL,
  `laudo_download_date` timestamp NULL DEFAULT NULL,
  `rx_digital` varchar(1) DEFAULT NULL,
  `negatoscopio` varchar(1) DEFAULT NULL,
  `qualidade` varchar(1) DEFAULT NULL,
  `comentarios_qualidade` varchar(200) DEFAULT NULL,
  `normal` varchar(1) DEFAULT NULL,
  `anormalidade_parenquima` varchar(1) DEFAULT NULL,
  `primarias` varchar(1) DEFAULT NULL,
  `secundarias` varchar(1) DEFAULT NULL,
  `zonas` varchar(6) DEFAULT NULL,
  `profusao` varchar(3) DEFAULT NULL,
  `grd_opacidade` varchar(1) DEFAULT NULL,
  `anormalidade_pleural` varchar(1) DEFAULT NULL,
  `placas_pleurais` varchar(1) DEFAULT NULL,
  `placas_parede_local` varchar(3) DEFAULT NULL,
  `placas_frontal_local` varchar(3) DEFAULT NULL,
  `placas_diafrag_local` varchar(3) DEFAULT NULL,
  `placas_outros_local` varchar(3) DEFAULT NULL,
  `placas_parede_calcif` varchar(3) DEFAULT NULL,
  `placas_frontal_calcif` varchar(3) DEFAULT NULL,
  `placas_diafrag_calcif` varchar(3) DEFAULT NULL,
  `placas_outros_calcif` varchar(3) DEFAULT NULL,
  `placas_extensao_o_d` varchar(5) DEFAULT NULL,
  `placas_extensao_o_e` varchar(5) DEFAULT NULL,
  `placas_largura_d` varchar(4) DEFAULT NULL,
  `placas_largura_e` varchar(4) DEFAULT NULL,
  `obliteracao` varchar(3) DEFAULT NULL,
  `espessamento_pleural` varchar(1) DEFAULT NULL,
  `espes_parede_local` varchar(3) DEFAULT NULL,
  `espes_frontal_local` varchar(3) DEFAULT NULL,
  `espes_parede_calcif` varchar(3) DEFAULT NULL,
  `espes_frontal_calcif` varchar(3) DEFAULT NULL,
  `espes_extensao_o_d` varchar(5) DEFAULT NULL,
  `espes_extensao_o_e` varchar(5) DEFAULT NULL,
  `espes_largura_d` varchar(4) DEFAULT NULL,
  `espes_largura_e` varchar(4) DEFAULT NULL,
  `outras_anormalidades` varchar(1) DEFAULT NULL,
  `simbolos` varchar(58) DEFAULT NULL,
  `comentarios_laudo` varchar(200) DEFAULT NULL,
  `reenviar_exame` int DEFAULT NULL,
  `enviado_por` varchar(30) DEFAULT NULL,
  `pagina_pdf_laudo` int DEFAULT NULL,
  `imagem_date` timestamp NULL DEFAULT NULL,
  `laudo_ecg` varchar(200) DEFAULT NULL,
  `laudo_ecg_outros` varchar(200) DEFAULT NULL,
  `frequencia_ecg` int DEFAULT NULL,
  `empresa` varchar(20) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,

  PRIMARY KEY (`id`),
  KEY `byExame` (`exame_id`),
  KEY `byEmpresa` (`empresa_id`),
  KEY `byCliente` (`cliente_id`),
  KEY `byArquivoExame` (`arquivo_exame`),
  KEY `byArquivo` (`arquivo_id`),
  KEY `byCreateDate` (`create_date`),
  KEY `byCRC` (`crc`,`ativo`),
  KEY `byProtocolo` (`protocolo`),
  KEY `byRG` (`rg`),
  KEY `byCPF` (`cpf`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
